name: Build and deploy

on:
  push:
    # branches:
    #   - main

jobs:
  build:
    name: Build and deploy to Heroku
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_APP_NAME_2: ${{ secrets.HEROKU_APP_NAME_2 }}
      HEROKU_PROCESS_TYPE: worker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Log in to Heroku Container registry
        run: docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
      - name: Build app
        run: |
          echo "Building ${HEROKU_APP_NAME}"
          docker build -t registry.heroku.com/${HEROKU_APP_NAME}/${HEROKU_PROCESS_TYPE} .
      # - name: Push app
      #   run: docker push registry.heroku.com/${HEROKU_APP_NAME}/${HEROKU_PROCESS_TYPE}:latest
      # - name: Release app
      #   run: heroku container:release -a ${HEROKU_APP_NAME} ${HEROKU_PROCESS_TYPE}
      # # App 2 (conditional)
      # - name: Build app 2
      #   if: env.HEROKU_APP_NAME_2 != null
      #   run: |
      #     echo "Building ${HEROKU_APP_NAME_2}"
      #     docker build -t registry.heroku.com/${HEROKU_APP_NAME_2}/${HEROKU_PROCESS_TYPE} .
      # - name: Push app 2
      #   if: env.HEROKU_APP_NAME_2 != null
      #   run: docker push registry.heroku.com/${HEROKU_APP_NAME_2}/${HEROKU_PROCESS_TYPE}:latest
      # - name: Release app 2
      #   if: env.HEROKU_APP_NAME_2 != null
      #   run: heroku container:release -a ${HEROKU_APP_NAME_2} ${HEROKU_PROCESS_TYPE}
